/**
 * Bridge runtime — locks 2 and 3 of the four-lock bridge design.
 *
 * A bridge shim (generated by `src/emit/bridges.ts`) is a thin Next.js App Router
 * route handler that wires one allowlisted server action to `createBridgeHandler`.
 * This module is the *only* logic behind that shim, exported at the package subpath
 * `opdeck/bridge`.
 *
 * Lock 2 — invisible posture: the handler is gated on a shared secret carried in the
 * `x-opdeck-bridge-token` request header, compared against the server-side
 * `OPDECK_BRIDGE_TOKEN` env var. If the env is unset, or the header is missing or
 * does not match, the handler returns `404` with an EMPTY body — indistinguishable
 * from a route that does not exist. An attacker without the token cannot tell a
 * bridge apart from a 404, so the mutation surface is invisible.
 *
 * Lock 3 — never swallow the app's own auth: once the token check passes, the handler
 * invokes the wrapped server action and lets any error it throws PROPAGATE. The
 * action's own session/authorization checks run exactly as they would when the app
 * calls it directly; a thrown `Unauthorized` (or any other error) is not caught,
 * reshaped, or masked here. It surfaces to Next.js's error handling like any error
 * thrown from a server action or route handler, so the app's real access control is
 * the boundary — the bridge never becomes a way around it.
 */

/** The request header carrying the bridge's shared secret. Documented and stable:
 * the MCP dispatch side (`src/mcp/server.ts`) sends the same header name. */
export const BRIDGE_TOKEN_HEADER = 'x-opdeck-bridge-token'

/** A Next.js App Router route handler: `(Request) => Promise<Response>`. */
export type BridgeRouteHandler = (req: Request) => Promise<Response>

/**
 * Wrap a server action `fn` as a token-gated POST route handler.
 *
 * The generated shim does exactly: `export const POST = createBridgeHandler(action)`.
 *
 * Behaviour:
 * - No `OPDECK_BRIDGE_TOKEN` env, or a missing/mismatched `x-opdeck-bridge-token`
 *   header -> `404` empty body (lock 2).
 * - Otherwise the JSON request body is parsed and passed as the sole argument to `fn`
 *   (an empty body passes `undefined`, for no-argument actions), and `fn`'s return
 *   value is serialised with `Response.json`.
 * - Errors thrown by `fn` are NOT caught — they propagate to Next.js (lock 3).
 */
export function createBridgeHandler<A, R>(fn: (arg: A) => R | Promise<R>): BridgeRouteHandler {
  return async function POST(req: Request): Promise<Response> {
    const expected = process.env.OPDECK_BRIDGE_TOKEN
    const provided = req.headers.get(BRIDGE_TOKEN_HEADER)
    // Lock 2: unset secret OR missing/wrong header -> invisible 404, empty body.
    if (!expected || provided !== expected) {
      return new Response(null, { status: 404 })
    }

    // Empty body -> `undefined` argument (a no-arg action). A non-empty body is parsed
    // as JSON; a malformed body throws here, but only for an already-authenticated
    // caller, and — like a server action's own errors — it is left to propagate.
    const raw = await req.text()
    const arg = raw.length === 0 ? undefined : JSON.parse(raw)

    // Lock 3: no try/catch. The action's own auth/session errors surface untouched.
    const result = await fn(arg as A)
    return Response.json(result)
  }
}
