/**
 * `build` orchestration — the library half of `opdeck build`.
 *
 * This is the tested seam the CLI is a thin shell over: it compiles the project
 * to IR, loads config, emits the bundle, generates bridges, folds the bridge
 * notes into coverage, writes `coverage.txt`, and returns the report plus the
 * counts the command needs to print. The CLI (`src/cli/build.ts`) does no
 * orchestration of its own — it resolves paths, calls `runBuild`, and prints.
 */

import { join } from 'node:path'
import { existsSync, rmSync, writeFileSync } from 'node:fs'
import { compile } from './compile.js'
import { loadConfig } from './config/load.js'
import { emitBundle } from './emit/bundle.js'
import { renderCoverage, type PublicCoverageInfo } from './emit/coverage.js'
import { generateBridges } from './emit/bridges.js'
import { prunePublicIR } from './emit/public.js'
import type { SemanticIR } from './ir/types.js'

export interface BuildResult {
  /** The compiled IR the whole build was derived from — bridge coverage folded in.
   * The plugin renders its build voice from this so the plugin and CLI describe the
   * SAME extraction. */
  ir: SemanticIR
  /** The rendered coverage report — printed by the CLI and written to disk. */
  report: string
  /** Absolute paths of every bundle file written. */
  written: string[]
  /** Bridge generation outcome (generated/removed drive the CLI's summary line). */
  bridges: ReturnType<typeof generateBridges>
  /** Public-storefront outcome when `public` is configured, else undefined. */
  public?: {
    /** Where the pruned `.agent-public/` bundle was written. */
    outDir: string
    /** Files written into the public bundle (relative paths). */
    written: string[]
    /** Actions surviving into the public surface. */
    count: number
  }
}

/**
 * The public bundle sits NEXT TO the internal one, at `<outDir>-public` (so the
 * default `.agent` yields `.agent-public`). Two structurally separate directories —
 * the internal artifact is never the public one.
 */
export function publicOutDir(outDir: string): string {
  return `${outDir}-public`
}

/**
 * Compile → config → emit → bridges → coverage for `projectDir`, writing the
 * bundle (and `coverage.txt`) into `outDir`. Both paths must already be resolved
 * to absolute. Throws on any error (a `ConfigError` is the deliberate
 * build-breaking case the CLI translates to a non-zero exit).
 */
export async function runBuild(projectDir: string, outDir: string): Promise<BuildResult> {
  const ir = await compile(projectDir)
  const config = await loadConfig(projectDir)
  const written = emitBundle(ir, outDir)
  // Bridges are written into the PROJECT (real Next.js routes), not the bundle out
  // dir, so this runs AFTER the emitters. Generation is gated on `config.bridges`;
  // a lock-4 coverage failure throws ConfigError, which the CLI handles.
  const bridges = generateBridges(ir, config, projectDir, { write: config?.bridges === true })
  // Fold the bridge generated/removed notes into the coverage report.
  ir.coverage.skipped.push(...bridges.coverage)

  // Public storefront (D2). When `public` is set, ALSO emit a pruned, token-free
  // bundle next to the internal one — regenerated by the SAME emitters over a filtered
  // IR, never post-edited. When it is unset, remove any stale public bundle so removing
  // the config never leaves an open door behind.
  const publicDir = publicOutDir(outDir)
  let publicResult: BuildResult['public']
  let publicInfo: PublicCoverageInfo | undefined
  if (config?.public !== undefined) {
    const pruned = prunePublicIR(ir, config.public)
    const publicWritten = emitBundle(pruned.ir, publicDir)
    // The public bundle carries its OWN coverage of just the pruned surface.
    writeFileSync(join(publicDir, 'coverage.txt'), renderCoverage(pruned.ir))
    publicInfo = {
      count: pruned.count,
      namedMutations: pruned.namedMutations,
      unmatchedNamed: pruned.unmatchedNamed,
    }
    publicResult = { outDir: publicDir, written: publicWritten, count: pruned.count }
  } else if (existsSync(join(publicDir, 'tools.json'))) {
    // Config turned the storefront off (or it never had one this build): a previously
    // emitted public bundle would keep serving unauthenticated, so retire it.
    rmSync(publicDir, { recursive: true, force: true })
  }

  const report = renderCoverage(ir, publicInfo)
  writeFileSync(join(outDir, 'coverage.txt'), report)
  return { ir, report, written, bridges, public: publicResult }
}
